### ISSUE TITLE
I get Telegram message with no video/gif

### ISSUE THREAD

**Issue by miaszh** [mluggy/teslabox#12]
Hi,

First thanks for this amazing project!
I've installed everything exc. the AWS which was complicated for me.
I get notified by Telegram, but with no video/gif included, here's the debug info:
`<html>
<body>

2023-04-14 04:47:49 | DEBUG | [queue/notify] /mnt/usb/TeslaCam/SentryClips/2023-04-14_04-47-40/event.json telegramed message 512927330 after 814ms
-- | -- | --
DEBUG | [queue/notify] /mnt/usb/TeslaCam/SentryClips/2023-04-14_04-47-40/event.json queued
INFO | [queue/early] /mnt/usb/TeslaCam/SentryClips/2023-04-14_04-47-40/event.json sent after 4762ms
DEBUG | [queue/early] /mnt/usb/TeslaCam/SentryClips/2023-04-14_04-47-40/event.json uploading: Tesla/shorts/2023-04-14/2023-04-14_04-47-40-sentry.gif
DEBUG | [queue/archive] /mnt/usb/TeslaCam/SentryClips/2023-04-14_04-47-40/event.json processing: ffmpeg -y -hide_banner -loglevel error -i /root/teslabox/src/assets/favicon.ico -ss 29 -t 30 -i /mnt/ram/c43c7b6130c9da4b09d7b5d8f81759ebff604cc6.mp4 -ss 29 -t 30 -i /mnt/ram/355d7880ed69ea8c5f889c0c0550bb3e811f560f.mp4 -ss 29 -t 30 -i /mnt/ram/f96dd5d56d60a4e57ff03fdb409f4c3ac02fd239.mp4 -ss 29 -t 30 -i /mnt/ram/0a9b84ebbe56fdd5d4078450ed549047a59a6618.mp4 -filter_complex "[0]scale=25:25 [icon]; [1]scale=480:360 [front]; [2]scale=1440:1080,pad=1920:1080 [right]; [3]scale=480:360 [back]; [4]scale=480:360 [left]; [right][left] overlay=1440:0 [rl]; [rl][front] overlay=1440:360 [rlf]; [rlf][back] overlay=1440:720 [all]; [all]drawtext=fontfile='/root/teslabox/src/assets/FreeSans.ttf':fontcolor=white:fontsize=25:borderw=1:bordercolor=black@1.0:x=38:y=1050:text='TeslaBox Tesla Sentry (Right) %{pts\:localtime\:1681436783}' [video]; [video][icon]overlay=8:1048" -preset veryfast -crf 23 /mnt/ram/725688ffbef8b7104b77319e096fedb735fa5a0c.mp4
DEBUG | [queue/archive] /mnt/usb/TeslaCam/SentryClips/2023-04-14_04-47-40/event.json queued
DEBUG | [queue/early] /mnt/usb/TeslaCam/SentryClips/2023-04-14_04-47-40/event.json processing: ffmpeg -y -hide_banner -loglevel error -i /root/teslabox/src/assets/favicon.ico -ss 39 -t 3 -i /mnt/ram/dddb14249718bb2471a3fd4f1faec69661503061.mp4 -filter_complex "[0]scale=15:15 [icon]; [1]fps=5,scale=640:480:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse,drawtext=fontfile='/root/teslabox/src/assets/FreeSans.ttf':fontcolor=white:fontsize=12:borderw=1:bordercolor=black@1.0:x=22:y=465:text='TeslaBox Tesla Sentry (Right) %{pts\:localtime\:1681436793}' [image]; [image][icon]overlay=5:462" -loop 0 /mnt/ram/4d8ba9feb36028996ce79c62ec227dd38c74da71.gif
DEBUG | [queue/early] /mnt/usb/TeslaCam/SentryClips/2023-04-14_04-47-40/event.json queued
DEBUG | [ping] 8.8.8.8 failed
INFO | [ping] connection established

</body>
</html>`

Any help appreciated.

**Comment by mluggy** [comment]
what's your notification settings? there are several options (from immediate, that contains nothing but the map and link to app), to early warning (that sends a short gif) and full that takes much longer.

check your s3 bucket to see if files are stored there. they must upload to s3 before telegram can fetch them.

**Comment by mluggy** [comment]
you probably haven't set the service file correctly (send a screenshot with secrets removed), or got the aws iam policy incorrect.

**Comment by miaszh** [comment]
![‏‏לכידה](https://user-images.githubusercontent.com/66449511/232162971-73f957f4-cdde-4cba-8295-11ea08484e08.PNG)
I guess something could be wrong with setting up the IAM user ..
the policy is 100% according to the guide, but I did not get access key at the end of the process, so I entered "Users" and then under "Access Keys" I did: "Create access key"

Did I miss something?

**Comment by mluggy** [comment]
yes your default region is incorrect. should be something along us-east-1. check s3 bucket and you'll see it there.

**Comment by miaszh** [comment]
AWS Region:
"US East (N. Virginia) us-east-1"

Is it what I should enter there?

**Comment by miaszh** [comment]
WOW !! Finally got it to work as expected! A lot of thanks for your help!
