### ISSUE TITLE
Flash drive doesn't appear as drive in Windows/MacOS

### ISSUE THREAD

**Issue by ranshn** [mluggy/teslabox#15]
I've gone through all the steps in the tutorial and I'm in the first step of the Setup section, where I connect the Teslabox to my computer via USB and wait for it to appear as a drive. Windows gives the following message:

> USB device not recognized
> The last USB device you connected to this computer malfunctioned, and Windows does not recognize it

Tried with a couple of USB type-C cables, and on a Macbook Pro which just doesn't respond at all when connecting the Teslabox via USB.

The teslabox is available on the network via SSH and Web. I raised the log level to DEBUG but there was nothing storage related

Any thoughts please?

**Comment by miaszh** [comment]
Did you try a short type-a to type-c cable?

**Comment by ranshn** [comment]
I bought a short type-c to type-c cable as per the instructions (which also doesn't work) but I don't really have a short a-c cable. Also the a-c cables that I'm trying, I can only try with a USB hub cause the laptops here don't have USB type-a anymore. If the cable is the suspect, then I can try a few more things like a short a-c cable and not using a USB hub/splitter. But I'm curious if the cable is actually the suspect

**Comment by miaszh** [comment]
Actually, to connect in the glovebox you will need a type-a to type-c anyway..
However, I would give it a try on a PC, without a hub..

**Comment by ranshn** [comment]
I was following the tutorial:

> Extra short, all males [USB-A to USB-C](https://s.click.aliexpress.com/e/_DCAMi91) or [USB-C to USB-C](https://s.click.aliexpress.com/e/_DBMVYjN) cable

I assumed that I can connect the Teslabox in the center console with a type-c - I assumed that's why the tutorial recommended buying type-a OR type-C. I'm still not sure whether or not type-c in the center console would work for teslabox.

**Comment by mluggy** [comment]
Yes, USB-C to USB-C is if you want the box in the center console. Some newer Tesla do not have data there.
The box still needs to show up as drive. No hub, and make sure the cable is data+power (vs. power only).

**Comment by senser-ran** [comment]
thanks @mluggy. I think getting the box to show up as a drive on Windows or MacOS is tricky - I don't think the current mounting options in the tutorial work. I'll continue trying while I wait for a USB A-C cable to show up because I realized late that center console doesn't have data anymore

**Comment by ranshn** [comment]
thanks @mluggy . I think getting the box to show up as a drive on Windows or MacOS is tricky - I don't think the current mounting options in the tutorial work. I'll continue trying while I wait for a USB A-C cable to show up because I realized late that center console doesn't have data anymore
