### ISSUE TITLE
Does the car power cycle or stop powering the USB port sometimes?

### ISSUE THREAD

**Issue by ranshn** [mluggy/teslabox#19]
From noticing that my Archive page gets cleared and reading in #18 that it is not persisted on the disk, I went and looked at the OS logs on the RPI and saw some occurrences of the system booting all by itself in the middle of the night. Interestingly, this seems to be happening daily at +/-30 mins around midnight. I couldn't find a reason for the reboot inside the OS logs, so I'm just assuming that it's the car that stops powering the box - either momentarily, or for a longer period of time.

Did anyone notice the car power cycling or anything that would stop powering the USB port in the glovebox? anything to do about it?
Having #18 merged would be great in order to circumvent it, because I'd like to have my archive page persist, especially if the car is going to power cycle the box every night..

**Comment by mluggy** [comment]
is the car connected to power and/or running sentry? if not, it will go to sleep.

**Comment by ranshn** [comment]
It is running Sentry all the time + was charging during these RPI reboots
