### ISSUE TITLE
Could use debugging info for TypeError

### ISSUE THREAD

**Issue by hurricanepkt** [mluggy/teslabox#2]
Keep getting an error : 

`connection failed: TypeError: Cannot read property 'body' of undefined`

without any indication as to what subsystem is causing the issue 

<img width="665" alt="image" src="https://user-images.githubusercontent.com/161399/188546474-02eafe69-9db0-4c66-8295-6b0219c3bd26.png">

**Comment by mluggy** [comment]
you're right. I'll try adding more. as for your issue, probably you didn't set up one of the NGROK env variables?

https://github.com/mluggy/teslabox/blob/928a1ca0c65d58a116784524e3175e1219cdb0ec/src/ngrok/index.js#L14

**Comment by mluggy** [comment]
fixed in 0.3.0
