### ISSUE TITLE
[ping] failed

### ISSUE THREAD

**Issue by michael5wong** [mluggy/teslabox#20]
Hi! Playing with the setup (using a USB LTE stick) - I can SSH into my pi, and ping google.com (and I can ping 8.8.8.8 too).  But the logs show:

2023-07-21 20:40:03 | DEBUG | [ping] 1.1.1.1 failed
DEBUG | [ping] 8.8.4.4 failed
DEBUG | [ping] 8.8.8.8 failed

Sentry recordings aren't being archived, and I'm not able to stream live videos. Any idea what I might have messed up in the configuration?  Thank you!

![image](https://github.com/mluggy/teslabox/assets/5488346/1a72fa5f-b7b0-474c-a65f-4a5ea8dee25a)

**Comment by mluggy** [comment]
it's ok for some pings to fail. where have you located the dongle? if you connect it physically to the USB of the pi it will not need wifi. Also, have you done the DNS step in tailscale?

**Comment by michael5wong** [comment]
I have the dongle physically connected to USB. There is no wifi connected right now while in my car.

I have done the DNS step (and when I SSH in, I can ping/resolve google.com). 

Could this DEBUG error be the issue?
`[usb] mount failed: Error: Command failed: mount /mnt/usb mount: /mnt/usb: /usb.bin is already mounted.`

**Comment by mluggy** [comment]
does the pi emulates properly as a usb drive in tesla? were you able to also connect it to your desktop/laptop and see the TeslaCam folder?

**Comment by michael5wong** [comment]
> does the pi emulates properly as a usb drive in tesla? were you able to also connect it to your desktop/laptop and see the TeslaCam folder?

Yes - I am able to see it.  I'm connecting through a USB LTE stick (not wifi) - could that be an issue? I can see the dashboard remotely via Tailscale, if that's helpful.

**Comment by mluggy** [comment]
it's fine to have a ping failed here and there. only 8 consecutive fails triggers a connection error.

**Comment by michael5wong** [comment]
I see.  I updated to the most recent - and I suspect this is better feedback/error? On the front homepage I'm only 13% of storage used. Does this make sense to error out?

<img width="1225" alt="image" src="https://github.com/mluggy/teslabox/assets/5488346/5292c8fd-7cc0-40dc-af52-ad4ed9ebd3a6">

**Comment by mluggy** [comment]
this will happen when you turn on streaming and uploading to the cloud, with too many angles. your box/internet cannot cope with so many files, eventually exhausting the temporary memory storage.try to upload only front angle.On 25 Sep 2023, at 4:10, michael5wong ***@***.***> wrote:﻿
I see.  I updated to the most recent - and I suspect this is better feedback/error? On the front homepage I'm only 13% of storage used. Does this make sense to error out?

**Comment by michael5wong** [comment]
Great!  This worked.  I'm getting the notifications - but not seeing the files online / seeing these errors now.  Any thoughts?  Thanks!


![image](https://github.com/mluggy/teslabox/assets/5488346/4c6a57d8-f03b-4a74-9b9f-4dc8f66f52e2)
