### ISSUE TITLE
Why does the storage fill up only when using Teslabox and not with normal storage use?

### ISSUE THREAD

**Issue by ranshn** [mluggy/teslabox#21]
I'm a new Teslabox user and I love it. For the first time since I started using it, the storage drive (128GB MicroSD in the RPI) filled up almost entirely, and it seems like Teslabox stopped working entirely or partially. I had an event that didn't send a notification, and saw this in the logs

_WARN	[usb] failed: Error: EIO: i/o error, scandir '/mnt/usb/TeslaCam/SentryClips/2023-07-15_21-00-15'_

I saw this in the [user manual](https://www.tesla.com/ownersmanual/model3/en_us/GUID-56703182-8191-4DAE-AF07-2FDC0EB64663.html)
_Note
When the internal storage reaches full capacity, new recordings from Alert and Alarm events overwrite the older recordings._

And also found online that normal users (not using any RPI or anything) are not required to take any action in order to clear up space or format the drive.

So - what are Teslabox users doing in terms of storage filling up? is using Teslabox preventing the car from deleting old files for some reason? I do realize that RPI mounts the storage as read-only, so I don't see why this would happen. But I'd love to know what long time users are actually doing in terms of storage. Is something not working as designed on my side?

**Comment by mluggy** [comment]
sentry events are overwritten, but dashcam events are not. this is how Tesla manage storage, and TeslaBox has nothing to do with it (it actually mounts the Tesla storage as read-only).

I suggest you'll turn on Low storage notification and occasiongly delete dashcam clips through the safety menu in car.

I also suggest having the dashcam app/icon visible at all time (drag it to your favorites), so you can see whether it is working and available before any drive.

**Comment by ranshn** [comment]
I understand, and I did manually delete all the dashcam videos, which doesn't seem to change anything. The car is reporting Sentry events when I get to it, but Teslabox doesn't.

W.r.t manually deleting files, isn't it true that normal Tesla users don't have to manually delete files and the car just handles it? This is what I find confusing

**Comment by mluggy** [comment]
currently, all Tesla users have to delete dashcam clips manually every now and then. only sentry clips are automatically overwritten.if teslabox doesn't deliver notifications, disconnect and reconnect the box and/or check the logs.On 4 Aug 2023, at 0:10, Ran ***@***.***> wrote:﻿
I understand, and I did manually delete all the dashcam videos, which doesn't seem to change anything. The car is reporting Sentry events when I get to it, but Teslabox doesn't.
W.r.t manually deleting files, isn't it true that normal Tesla users don't have to manually delete files and the car just handles it? This is what I find confusing
