### ISSUE TITLE
df: /mnt/usb: No such file or directory

### ISSUE THREAD

**Issue by whitesm2000** [mluggy/teslabox#22]
Hi. I got this error. Tried to troubleshoot using Phind (GPT4), see the link. 

Can you let me know what the issue might be? I formatted and re-installed the raspberry OS and repeated the process with the same result. 

root@jptesla3box:~/teslabox# systemctl status teslabox
● teslabox.service - TeslaBox
     Loaded: loaded (/lib/systemd/system/teslabox.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2023-08-18 14:53:27 EDT; 3s ago
    Process: 6978 ExecStart=/usr/bin/node /root/teslabox/src/index.js (code=exited, status=1/FAILURE)
   Main PID: 6978 (code=exited, status=1/FAILURE)
        CPU: 1.870s

Aug 18 14:53:45 jptesla3box systemd[1]: Started TeslaBox.
Aug 18 14:53:47 jptesla3box node[7038]: (node:7038) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Aug 18 14:53:47 jptesla3box node[7038]: Please migrate your code to use AWS SDK for JavaScript (v3).
Aug 18 14:53:47 jptesla3box node[7038]: For more information, check the migration guide at https://a.co/7PzMCcy
Aug 18 14:53:47 jptesla3box node[7038]: (Use `node --trace-warnings ...` to show where the warning was created)
Aug 18 14:53:47 jptesla3box node[7038]: FATAL [main] teslabox failed: Error: Command failed: df -B G /mnt/usb
Aug 18 14:53:47 jptesla3box node[7038]: df: /mnt/usb: No such file or directory
Aug 18 14:53:47 jptesla3box systemd[1]: teslabox.service: Main process exited, code=exited, status=1/FAILURE
Aug 18 14:53:47 jptesla3box systemd[1]: teslabox.service: Failed with result 'exit-code'.
Aug 18 14:53:47 jptesla3box systemd[1]: teslabox.service: Consumed 1.816s CPU time.
Aug 18 14:53:52 jptesla3box systemd[1]: teslabox.service: Scheduled restart job, restart counter is at 4.

https://www.phind.com/search?cache=c4fc1be3-2f07-441e-8ba5-ef020ffc9867

**Comment by whitesm2000** [comment]
NVM. It started running now:
root@jptesla3box:~/teslabox# systemctl status teslabox
● teslabox.service - TeslaBox
     Loaded: loaded (/lib/systemd/system/teslabox.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-08-18 15:02:12 EDT; 17min ago
   Main PID: 8491 (node)
      Tasks: 11 (limit: 8755)
        CPU: 5min 41.838s
     CGroup: /system.slice/teslabox.service
             └─8491 /usr/bin/node /root/teslabox/src/index.js

Aug 18 15:02:12 jptesla3box systemd[1]: Started TeslaBox.
Aug 18 15:02:13 jptesla3box node[8491]: (node:8491) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Aug 18 15:02:13 jptesla3box node[8491]: Please migrate your code to use AWS SDK for JavaScript (v3).
Aug 18 15:02:13 jptesla3box node[8491]: For more information, check the migration guide at https://a.co/7PzMCcy
Aug 18 15:02:13 jptesla3box node[8491]: (Use `node --trace-warnings ...` to show where the warning was created)

**Comment by whitesm2000** [comment]
It did try 78 times to finally work. Not sure what the issue was. 

Aug 18 15:02:07 jptesla3box node[8470]: df: /mnt/usb: No such file or directory
Aug 18 15:02:07 jptesla3box systemd[1]: teslabox.service: Main process exited, code=exited, status=1/FAILURE
Aug 18 15:02:07 jptesla3box systemd[1]: teslabox.service: Failed with result 'exit-code'.
Aug 18 15:02:07 jptesla3box systemd[1]: teslabox.service: Consumed 1.815s CPU time.
Aug 18 15:02:12 jptesla3box systemd[1]: teslabox.service: Scheduled restart job, restart counter is at 78.
Aug 18 15:02:12 jptesla3box systemd[1]: Stopped TeslaBox.
Aug 18 15:02:12 jptesla3box systemd[1]: teslabox.service: Consumed 1.815s CPU time.
Aug 18 15:02:12 jptesla3box systemd[1]: Started TeslaBox.
Aug 18 15:02:13 jptesla3box node[8491]: (node:8491) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Aug 18 15:02:13 jptesla3box node[8491]: Please migrate your code to use AWS SDK for JavaScript (v3).
Aug 18 15:02:13 jptesla3box node[8491]: For more information, check the migration guide at https://a.co/7PzMCcy
Aug 18 15:02:13 jptesla3box node[8491]: (Use `node --trace-warnings ...` to show where the warning was created)

**Comment by mluggy** [comment]
usually means one or more serious weren't completed, probarbly editing the fstab or running mass_storage.

anyhow, I'm glad you got it to work.
