### ISSUE TITLE
[usb] failed: Error: ENOSPC: no space left on device

### ISSUE THREAD

**Issue by whitesm2000** [mluggy/teslabox#23]
<html>
<body>

2023-08-18 21:42:31 | WARN | [usb] failed: Error: ENOSPC: no space left on device, copyfile '/mnt/usb/TeslaCam/RecentClips/2023-08-18_21-41-14-back.mp4' -> '/mnt/ram/b76701475e1609710172fcc9042a6f997362578f.mp4'
-- | -- | --

</body>
</html>

2% used (7 of 437GB)
 

I believe there is plenty of space.

**Comment by mluggy** [comment]
this error is because of memory space, usually when you try to stream to cloud with too many angles, too high quality and/or your connection is lousy (so files keeps piling).

what board and settings are you using?

**Comment by whitesm2000** [comment]
I had Copy streams to cloud setting enabled with High quality with all angles. I stopped streaming to cloud and I think the error has stopped. 

PI4B-8GB is the model of raspberry being used.

**Comment by whitesm2000** [comment]
Looks like it is doing again. Should I lower the quality of the video? Stream to cloud is disabled. 

<html>
<body>


2023-08-19 11:07:10 | DEBUG | [queue/stream] /mnt/usb/TeslaCam/RecentClips/2023-08-19_10-01-46-left_repeater.mp4 processing: ffmpeg -y -hide_banner -loglevel error -i /root/teslabox/src/assets/favicon.ico -i /mnt/ram/dd575294dce6e2cb4a95bd6fb3536704dd10824f.mp4 -filter_complex "[0]scale=18:18 [icon]; [1]scale=1024:768,drawtext=fontfile='/root/teslabox/src/assets/FreeSans.ttf':fontcolor=white:fontsize=14:borderw=1:bordercolor=black@1.0:x=25:y=750:text='TeslaBox JP Tesla 3 (Left) %{pts\:localtime\:1692453706}' [video]; [video][icon]overlay=5:747" -preset veryfast -crf 23 /mnt/ram/8b36898bf2f6b4af8345880eedc06c3501b41733.mp4
-- | -- | --
INFO | [queue/stream] /mnt/usb/TeslaCam/RecentClips/2023-08-19_10-01-46-front.mp4 streamed after 3858447ms
DEBUG | [ping] 9.9.9.9 failed
DEBUG | [ping] 1.0.0.1 failed
WARN | [usb] failed: Error: ENOSPC: no space left on device, copyfile '/mnt/usb/TeslaCam/RecentClips/2023-08-19_11-05-23-back.mp4' -> '/mnt/ram/1d7f74a5d350da72acb05a8eee727bd804752b8c.mp4'
DEBUG | [queue/stream] /mnt/usb/TeslaCam/RecentClips/2023-08-19_10-01-46-front.mp4 processing: ffmpeg -y -hide_banner -loglevel error -i /root/teslabox/src/assets/favicon.ico -i /mnt/ram/b89649a86401104a7fd6a77e95ed3f5921780418.mp4 -filter_complex "[0]scale=18:18 [icon]; [1]scale=1024:768,drawtext=fontfile='/root/teslabox/src/assets/FreeSans.ttf':fontcolor=white:fontsize=14:borderw=1:bordercolor=black@1.0:x=25:y=750:text='TeslaBox JP Tesla 3 (Front) %{pts\:localtime\:1692453706}' [video]; [video][icon]overlay=5:747" -preset veryfast -crf 23 /mnt/ram/11aaa0570069392b84638a5a835a94de7f2ac154.mp4
INFO | [queue/stream] /mnt/usb/TeslaCam/RecentClips/2023-08-19_10-00-46-back.mp4 streamed after 3879522ms


</body>
</html>

<html>
<body>


2023-08-19 11:06:34 | WARN | [usb] failed: Error: ENOSPC: no space left on device, copyfile '/mnt/usb/TeslaCam/RecentClips/2023-08-19_11-05-23-right_repeater.mp4' -> '/mnt/ram/16f6b2fed0ed7e9c7b835d275a9db8ac94e3a705.mp4'
-- | -- | --
DEBUG | [queue/stream] /mnt/usb/TeslaCam/RecentClips/2023-08-19_11-05-23-left_repeater.mp4 queued


</body>
</html>

<html>
<body>


2023-08-19 11:06:02 | INFO | [queue/stream] /mnt/usb/TeslaCam/RecentClips/2023-08-19_10-00-46-right_repeater.mp4 streamed after 3848362ms
-- | -- | --
WARN | [usb] failed: Error: ENOSPC: no space left on device, copyfile '/mnt/usb/TeslaCam/RecentClips/2023-08-19_11-04-23-back.mp4' -> '/mnt/ram/3ce572b8be3ed16e370c9973f379158c34af2daf.mp4'
DEBUG | [queue/stream] /mnt/usb/TeslaCam/RecentClips/2023-08-19_11-04-23-right_repeater.mp4 queued


</body>
</html>

<html>
<body>


2023-08-19 11:05:32 | DEBUG | [queue/stream] /mnt/usb/TeslaCam/RecentClips/2023-08-19_10-00-46-right_repeater.mp4 processing: ffmpeg -y -hide_banner -loglevel error -i /root/teslabox/src/assets/favicon.ico -i /mnt/ram/b207ecade62a015b43f5aca078955e225b9428ee.mp4 -filter_complex "[0]scale=18:18 [icon]; [1]scale=1024:768,drawtext=fontfile='/root/teslabox/src/assets/FreeSans.ttf':fontcolor=white:fontsize=14:borderw=1:bordercolor=black@1.0:x=25:y=750:text='TeslaBox JP Tesla 3 (Right) %{pts\:localtime\:1692453646}' [video]; [video][icon]overlay=5:747" -preset veryfast -crf 23 /mnt/ram/361b5e6f38ed818cbc5a7e883cd10750e16a7467.mp4
-- | -- | --
WARN | [queue/stream] /mnt/usb/TeslaCam/RecentClips/2023-08-19_10-00-46-left_repeater.mp4 failed: Error: Command failed: ffmpeg -y -hide_banner -loglevel error -i /root/teslabox/src/assets/favicon.ico -i /mnt/ram/e4691fd195d1ab15fe8976710521ef5d9c457c54.mp4 -filter_complex "[0]scale=18:18 [icon]; [1]scale=1024:768,drawtext=fontfile='/root/teslabox/src/assets/FreeSans.ttf':fontcolor=white:fontsize=14:borderw=1:bordercolor=black@1.0:x=25:y=750:text='TeslaBox JP Tesla 3 (Left) %{pts\:localtime\:1692453646}' [video]; [video][icon]overlay=5:747" -preset veryfast -crf 23 /mnt/ram/3293af4693848cf8639d39ea58e4a84305650855.mp4 av_interleaved_write_frame(): No space left on device Error writing trailer of /mnt/ram/3293af4693848cf8639d39ea58e4a84305650855.mp4: No space left on device
DEBUG | [queue/stream] /mnt/usb/TeslaCam/RecentClips/2023-08-19_11-04-23-left_repeater.mp4 queued


</body>
</html>

**Comment by mluggy** [comment]
just reset the box (pull it out from power after long pressing recording on the main car screen). reconnect, and click record once again to wait for the red mark.

reset should clear all memory storage.

**Comment by whitesm2000** [comment]
Will try that. Can I reboot using linux command vis SSH or would that lead to some issues?

**Comment by mluggy** [comment]
i usually reboot by turning off sentry (or parking at home), which makes the car go to sleep if you aren't checking it with the ago.

**Comment by whitesm2000** [comment]
Got it. I will try that. Thanks for the help.

**Comment by whitesm2000** [comment]
Rebooted and it seems the error continues:

<html>
<body>


2023-08-19 18:00:00 | WARN | [usb] failed: Error: ENOSPC: no space left on device, copyfile '/mnt/usb/TeslaCam/RecentClips/2023-08-19_17-58-37-right_repeater.mp4' -> '/mnt/ram/216038ed6d0388b21b625a41b5ef033bf11975c9.mp4'
-- | -- | --
WARN | [usb] failed: Error: ENOSPC: no space left on device, copyfile '/mnt/usb/TeslaCam/RecentClips/2023-08-19_17-58-37-back.mp4' -> '/mnt/ram/fac408d562f51c446955599e2f3d0bb70662e296.mp4'
WARN | [usb] failed: Error: ENOSPC: no space left on device, copyfile '/mnt/usb/TeslaCam/RecentClips/2023-08-19_17-58-37-left_repeater.mp4' -> '/mnt/ram/90aa77a79d6dde3849546052bb97218baac2250e.mp4'


</body>
</html>

**Comment by mluggy** [comment]
make sure your previous setting got saved and you aren't uploading stream to cloud.
other than that, you'll need to ssh the box and do:

sudo df -h

then

sudo cat /etc/fstab

paste these here to make sure your drive/memory settings are correct

**Comment by whitesm2000** [comment]
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       469G  443G  7.7G  99% /
devtmpfs        3.6G     0  3.6G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           1.6G  1.5M  1.6G   1% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           3.9G  3.8G   21M 100% /mnt/ram
/dev/mmcblk0p1  255M   31M  225M  13% /boot
tmpfs           782M   20K  782M   1% /run/user/1000
overlay         469G  443G  7.7G  99% /var/lib/docker/overlay2/5a0bef566a325415741d173b97276a96af9b40d9cf05bf8c163e694b812921e1/merged
overlay         469G  443G  7.7G  99% /var/lib/docker/overlay2/9bac0c738acd37c9568eb01a58a5004cdcbbe20be8f565fa3c0d549bda377538/merged
overlay         469G  443G  7.7G  99% /var/lib/docker/overlay2/af78c52e8d2c80b5e050ffeb96ddbea9865ee29823f1b759e095506a2a0d9c52/merged
overlay         469G  443G  7.7G  99% /var/lib/docker/overlay2/4314698961cc31847d1b72adb36ffc11f9580cdb160c05b32720940d16cb5134/merged
shm              64M   28K   64M   1% /var/lib/docker/containers/861d3537aa77f5140b85bacf137613866a6e48c0c02c4b853394a1cffe6ca932/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/83484f1a1a87f9342d666799d0eaf0784de3540d02737bba45aeebab98d2b8e0/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/7a568b7976705cde5dfd7fef37a67373b7d46eff9c99f378df338400e3c2063e/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/0900f3cc27fe8da339f2f6e42ee28fbc034caf9f9a991a9892a57795d3f2a10d/mounts/shm
/dev/loop0      437G   15G  423G   4% /mnt/usb

**Comment by whitesm2000** [comment]
proc            /proc           proc    defaults          0       0
PARTUUID=a21cb8ff-01  /boot           vfat    defaults          0       2
PARTUUID=a21cb8ff-02  /               ext4    defaults,noatime  0       1
# a swapfile is not a swap partition, no line here
#   use  dphys-swapfile swap[on|off]  for that
/usb.bin /mnt/usb vfat auto,noexec,nouser,ro,sync 0 0
tmpfs /mnt/ram tmpfs nodev,nosuid,size=50% 0 0

**Comment by mluggy** [comment]
have you also installed TeslaMate on the box?
Configuration looks fine, have you restarted the box since?

**Comment by whitesm2000** [comment]
Yes, I have installed TeslaMate and restarted the box (turned off Sentry, the car went to sleep, and I woke it up).

**Comment by whitesm2000** [comment]
I changed every setting to lowest and disabled streaming (itself, to cloud was disabled previously) to see if this helps. I will let you know. THanks.

**Comment by whitesm2000** [comment]
Live view worked, no error. But I wonder if live view is interfering with sending the notification (wasn't getting notification). I will play with it some more and see.

**Comment by mluggy** [comment]
if you're not getting a notification (because of configuration most likely or internet connectivity) then it is not ending the process, and files will continue to accumulate until you run out of space.

**Comment by whitesm2000** [comment]
I see. Makes sense. Thanks.

**Comment by whitesm2000** [comment]
With every being set up lowest and the stream turned off completely seems to have fixed the issue for now.

**Comment by mluggy** [comment]
great to hear, closing for now.
