### ISSUE TITLE
Not getting any emails or telegram messages

### ISSUE THREAD

**Issue by whitesm2000** [mluggy/teslabox#25]
Videos are being uploaded to Amazon S3 just fine, but not getting any emails or telegram messages. No error messages in the log. There was an error message about Amazon region being incorrect, but it was changed, but still no email since then.

**Comment by whitesm2000** [comment]
Oddly enough it just sent me emails and telegram messages. Maybe the device was overwhelmed when I set to send stream to clouds.

**Comment by mluggy** [comment]
yes. streaming to cloud through more than one angle for a long time, especially if your internet isn't stable, will overwhelm the box.

try to narrow it down to one angle (usually, front).
