### ISSUE TITLE
Use other AWS S3 compatible service

### ISSUE THREAD

**Issue by jheredianet** [mluggy/teslabox#26]
Question/Idea: Is it possible to use other S3 compatible cloud service?

Since there are other convenient S3 cloud service out there, it would be interesting to setup other buckets to use.

**Comment by mluggy** [comment]
I do not believe it is currently supported, as I use AWS native SDK (region and bucket name). Curious what cloud service specifically you had in mind?

**Comment by jheredianet** [comment]
For example:
- Wasabi cloud (https://wasabi.com/)
- iDrive (https://www.idrive.com/)

Both not costs for uploads and downloads traffic. 
Actually, could be any other s3 compatible bucket as many other tools in the market offer.
