### ISSUE TITLE
Idea: Display in the UI the free storage status, Warn and message at 90%.

### ISSUE THREAD

**Issue by yakirdm** [mluggy/teslabox#3]
Idea: Display in the UI the free storage space status, warn at 90% used.
also @Genadyo suggested sending a message in Telegram.

Thank you for the great work and solution.

**Comment by mluggy** [comment]
working on this:
<img width="295" alt="image" src="https://user-images.githubusercontent.com/989188/195057880-bb39731d-b508-40d9-90d4-fde196a426f2.png">

and an alert every time the teslabox starts.

**Comment by mluggy** [comment]
done in 0.6.0
