### ISSUE TITLE
Run Tesla Android

### ISSUE THREAD

**Issue by jheredianet** [mluggy/teslabox#30]
Question:

Hi, since I've since in the documentation: 

`
If your run other projects, like Tesla Android, change the port number to avoid conflict
Environment="ADMIN_PORT=80"
`

Could you give an idea how to have both projects together, since Tesla Android has its own img file to burn the SD card, so not sure how to add Teslabox above it. 

Thanks for any help.

**Comment by mluggy** [comment]
change the ADMIN_PORT to 8080, 81 or 9000 and you’ll be able to browse teslabox using, say http://your.tailscale.ip:8080 <http://your.tailscale.ip:8080/> instead.
It will free port 80 to whatever other project you’re running.

**Comment by mluggy** [comment]
understood. so i'm guessing TeslaAndroid is some form of linux? simply start the same process there minus the image part (start with #7).

**Comment by miaszh** [comment]
TeslaAndroid writes a modified version of android to run on rpi4, its not linux, hence, i think it'd be impossible to run them both on one device, also the memory mounting seems to be impossible then..

**Comment by jheredianet** [comment]
> TeslaAndroid writes a modified version of android to run on rpi4, its not linux, hence, i think it'd be impossible to run them both on one device, also the memory mounting seems to be impossible then..

Thanks for clarifying that. You're write, if Tesla Android is not linux it would be impossible to make it compatible.

**Comment by jheredianet** [comment]
> can you ssh the TeslaAndroid and send the output of this run:
> 
> ```
> cat /etc/os-release
> lsb_release -a
> hostnamectl
> uname -r
> ```

Actually, TeslaAndroid doesn't have access by ssh, what is possible is to access by USB - ADB like other android phones. Like @miaszh pointed it is really a modified version of Android to run on rpi4.

**Comment by mluggy** [comment]
In that case they are unlikely to run in parallel. sorry.
