### ISSUE TITLE
v1.0.4 Cinematic Sentry mode processing takes a very long time.

### ISSUE THREAD

**Issue by sompong-ttbspark** [mluggy/teslabox#34]
I am currently facing an issue with the process of archiving files to S3 in Cinematic Sentry Mode. I've noticed that the files generated as part of the cinematic process in the 'mnt/ram/' folder are excessively large, leading to a significantly prolonged processing time. If there are more than 8 files in the 'usb/TeslaCam/SentryClips' folder, I suspect that the file merging process for Cinematic Sentry Mode may be encountering some difficulties.

**Processing takes about 30 minutes.**
<img width="1303" alt="Screenshot 2566-10-09 at 02 24 33" src="https://github.com/mluggy/teslabox/assets/128113271/4ce06c8b-6b75-49fd-8ec1-c47554fa8b87">

**temporary files before uploading to S3.**
<img width="539" alt="Screenshot 2566-10-09 at 02 27 33" src="https://github.com/mluggy/teslabox/assets/128113271/94c9fea7-ae6b-4cf5-8c24-05644f93e7f5">

**Comment by jheredianet** [comment]
Same behaviour here. I had to disable cinematic mode (I was using medium as quality)

**Comment by sompong-ttbspark** [comment]
> Same behaviour here. I had to disable cinematic mode (I was using medium as quality)

Thank you for the quick solution.

**Comment by mluggy** [comment]
Hi guys, try 1.0.5. I've cleared out the null filters and set the refresh rate back to 24. It should yield smaller, faster files.
