### ISSUE TITLE
Tesla didn't "auto detect" crash

### ISSUE THREAD

**Issue by hurricanepkt** [mluggy/teslabox#4]
I unplugged the teslabox pi within 5 minutes of the crash while it was on "auto" record. 

Any idea where the longer currently written video file might be stored?

**Comment by hurricanepkt** [comment]
recognize this isn't 100% on topic but file storage location would be helpful in documentation

**Comment by mluggy** [comment]
Try connecting TeslaBox via USB cable to your desktop and it should appear as standard USB, with all the raw files/folders showing.

**Comment by mluggy** [comment]
Videos that were recording but didn't save should be on RecentClips.
Videos saved should be on SavedClips.
